package: matomo
version: '0.0.2-dev'
author: 'skerbis'
supportpage: https://github.com/skerbis/matomo

page:
    title: 'Matomo'
    perm: matomo[]
    pjax: true
    icon: rex-icon fa-code
    subpages:
        dashboard: { title: 'translate:matomo_dashboard'}
        settings:
                title: 'translate:matomo_settings'
                perm: admin[]

requires:
    redaxo: ^5.7.0
