package: matomo
version: '1.0.0-beta1'
author: 'skerbis'
supportpage: https://github.com/skerbis/matomo

page:
    title: 'Matomo'
    perm: matomo[]
    pjax: true
    icon: rex-icon rex-icon-seo
    subpages:
        dashboard: { title: 'translate:matomo_dashboard'}
        settings:
                title: 'translate:matomo_settings'
                perm: admin[]

requires:
    redaxo: ^5.7.0
