package: matomo
version: '1.1.2-dev'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/matomo

page:
    title: 'Matomo'
    perm: matomo[]
    pjax: true
    icon: rex-icon rex-icon-seo
    subpages:
        dashboard: { title: 'translate:matomo_dashboard', icon: rex-icon rex-icon-seo}
        settings:
                title: 'translate:matomo_settings'
                perm: admin[] 
        help: { title: 'translate:matomo_help', itemclass: pull-right, icon: rex-icon fa-question-circle, subPath: README.md}        

requires:
    php:
        extensions: [curl]
    redaxo: ^5.7.0
    
