package: matomo
version: '2.0.0'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/matomo

page:
    title: 'translate:matomo_title'
    perm: matomo[]
    pjax: true
    icon: 'rex-icon rex-icon-seo'
    subpages:
        overview: { title: 'translate:matomo_overview', icon: 'rex-icon rex-icon-template', perm: matomo[overview]}
        config: { title: 'Konfiguration', icon: 'rex-icon rex-icon-config', perm: admin}
        domains: { title: 'Domains', icon: 'rex-icon rex-icon-structure', perm: admin}
        settings:
                title: 'translate:matomo_settings'
                perm: admin
        help: { title: 'translate:matomo_help', itemclass: pull-right, icon: 'rex-icon fa-question-circle', subPath: README.md}        

requires:
    php:
        version: '>=8.2'   
    redaxo: ^5.16.1

default_config:
    matomo_url: ''
    matomo_path: ''
    admin_token: ''
    user_token: ''
    matomo_user: ''
    matomo_password: ''
    api_timeout: 30
    ssl_verify: false
    anonymize_ip: false
    cookieless_tracking: false
    respect_dnt: false
    show_top_pages: false
