package: matomo
version: '1.2.2'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/matomo

page:
    title: 'translate:matomo_title'
    perm: matomo[]
    pjax: true
    icon: rex-icon rex-icon-seo
    subpages:
        overview: { title: 'translate:matomo_overview', icon: rex-icon rex-icon-template}
        dashboard: { title: 'translate:matomo_dashboard', icon: rex-icon rex-icon-seo}
        settings:
                title: 'translate:matomo_settings'
                perm: admin[]
        config: { title: 'Konfiguration', icon: rex-icon rex-icon-config, perm: admin[]}
        domains: { title: 'Domains', icon: rex-icon rex-icon-structure}
        help: { title: 'translate:matomo_help', itemclass: pull-right, icon: rex-icon fa-question-circle, subPath: README.md}        

requires:
    php:
        extensions: [curl]
        version: '>=7.1'   
    redaxo: ^5.7.0
